version: '3.8'

services:
  db:
    container_name: simple_banking_db_1
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_omno_bankingGo2:/var/lib/postgresql/data

  app:
    image: simplebank:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - DB_SOURCE=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  postgres_data_omno_bankingGo2:
